const KEY='jh_resolve_data_v1';
const seed=[
{id:'CH-1001',title:'Flooded access road near low-lying settlement',category:'Flood',district:'East Singhbhum',priority:'High',status:'Routing',description:'Road becomes unusable after heavy rainfall. Need drainage and safe pedestrian access.',created:'Today 18:42',student:'Unassigned',support:'Seeking industry support'},
{id:'CH-1002',title:'Community water contamination concern',category:'Water',district:'Ranchi',priority:'Medium',status:'In Progress',description:'Residents need a low-cost water-quality monitoring approach.',created:'Today 15:10',student:'Team AquaSense',support:'Mentor matched'},
{id:'CH-1003',title:'Slope instability near rural road',category:'Landslide',district:'Latehar',priority:'High',status:'New',description:'Cracks observed near a road cut after prolonged rain.',created:'Yesterday',student:'Unassigned',support:'Needs geotechnical mentor'}];
function load(){let x=localStorage.getItem(KEY);if(!x){localStorage.setItem(KEY,JSON.stringify({challenges:seed,pledges:[],telemetry:[]}));return {challenges:seed,pledges:[],telemetry:[]}}return JSON.parse(x)}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.querySelector('.toast');if(!t)return;t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2800)}
function mapsLink(c){return c.latitude&&c.longitude?`https://www.google.com/maps?q=${encodeURIComponent(c.latitude+','+c.longitude)}`:''}
function challengeCard(c,actions=true){return `<div class="report"><div class="report-head"><strong>${esc(c.title)}</strong><span class="priority-${String(c.priority||'Low').toLowerCase()}">${esc(c.priority||'Low')}</span></div><div style="margin:8px 0"><span class="tag">${esc(c.category)}</span> <span class="tag">${esc(c.district)}</span> <span class="tag">${esc(c.status)}</span></div>${c.photo?`<img class="report-photo" src="${c.photo}" alt="Citizen disaster evidence">`:''}<p class="muted small">${esc(c.description)}</p>${c.latitude&&c.longitude?`<div class="location-detail">📍 <b>GPS:</b> ${esc(Number(c.latitude).toFixed(6))}, ${esc(Number(c.longitude).toFixed(6))}${c.accuracy?` <span class="muted">(±${esc(Math.round(c.accuracy))} m)</span>`:''} <a class="map-link" href="${mapsLink(c)}" target="_blank" rel="noopener">Open map ↗</a></div>`:'<div class="small muted">📍 Location not attached</div>'}<div class="small muted">${esc(c.id)} • ${esc(c.created)}</div>${actions?`<div style="margin-top:13px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn primary" onclick="claim('${c.id}')">Claim project</button><button class="btn" onclick="route('${c.id}')">Smart route</button></div>`:''}</div>`}
function claim(id){const d=load(),c=d.challenges.find(x=>x.id===id);if(c){c.status='In Progress';c.student='Demo University Team';save(d);toast('Project claimed by Demo University Team');renderStudent()}}
function route(id){const d=load(),c=d.challenges.find(x=>x.id===id);if(c){c.status='Routing';save(d);toast(`Smart routing triggered for ${c.id}`);sendN8n(c)}}
async function sendN8n(c){const url=localStorage.getItem('n8n_webhook');if(!url)return;try{await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:'challenge.created',challenge:c,routeTo:routeDepartment(c)})})}catch(e){console.warn(e)}}
function routeDepartment(c){const s=(c.category+' '+c.title+' '+c.description).toLowerCase();if(/flood|drain|road|bridge|slope|landslide/.test(s))return 'Civil Engineering';if(/water|quality|contamination/.test(s))return 'Environmental / Civil Engineering';if(/health|medical|disease/.test(s))return 'Biomedical / Social Science';if(/power|electric|energy/.test(s))return 'Electrical Engineering';return 'Multidisciplinary Innovation Cell'}
function renderStudent(){const el=document.querySelector('#student-list');if(!el)return;const d=load();el.innerHTML=d.challenges.map(c=>challengeCard(c)).join('')}
function renderCitizen(){const el=document.querySelector('#citizen-list');if(!el)return;el.innerHTML=load().challenges.slice().reverse().map(c=>challengeCard(c,false)).join('')}
function renderIndustry(){const d=load();const el=document.querySelector('#industry-list');if(!el)return;el.innerHTML=d.challenges.filter(c=>c.status!=='Resolved').map(c=>`<div class="report"><strong>${esc(c.title)}</strong><p class="muted small">${esc(c.district)} • ${esc(c.category)} • Priority: ${esc(c.priority)}</p><button class="btn primary" onclick="pledge('${c.id}')">Pledge support</button></div>`).join('')}
function pledge(id){const d=load();d.pledges.push({id,partner:'Demo Industry Partner',type:'Funding + Mentor',at:new Date().toLocaleString()});save(d);toast('Industry pledge recorded');renderIndustry()}
function renderGov(){const d=load();const high=d.challenges.filter(x=>x.priority==='High').length;document.querySelector('#total').textContent=d.challenges.length;document.querySelector('#high').textContent=high;document.querySelector('#progress').textContent=d.challenges.filter(x=>x.status==='In Progress').length;document.querySelector('#pledges').textContent=d.pledges.length;document.querySelector('#gov-list').innerHTML=d.challenges.map(c=>challengeCard(c,false)).join('');const t=document.querySelector('#telemetry');if(t)t.innerHTML=(d.telemetry||[]).slice(-6).reverse().map(x=>`<div class="report"><strong>${esc(x.device)}</strong><span class="tag">Water ${x.water}%</span> <span class="tag">Temp ${x.temp}°C</span><div class="small muted">${esc(x.time)} • ${x.alert?'THRESHOLD BREACH':'Normal'}</div></div>`).join('')||'<div class="empty">No telemetry yet. Start the simulator.</div>'}
function compressImage(file,maxWidth=1280,quality=.72){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,maxWidth/img.width);const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',quality))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
function setLocation(lat,lon,accuracy){const form=document.querySelector('#challenge-form');if(!form)return;form.latitude.value=lat;form.longitude.value=lon;form.accuracy.value=accuracy||'';const status=document.querySelector('#location-status');status.innerHTML=`<b>Location captured.</b> ${lat.toFixed(6)}, ${lon.toFixed(6)}${accuracy?` • accuracy ±${Math.round(accuracy)} m`:''}`;const map=document.querySelector('#map-preview');map.hidden=false;map.innerHTML=`<iframe title="Selected disaster location" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=${lon-.006}%2C${lat-.004}%2C${lon+.006}%2C${lat+.004}&layer=mapnik&marker=${lat}%2C${lon}"></iframe>`}
function initLocation(){document.querySelector('#get-location')?.addEventListener('click',()=>{const status=document.querySelector('#location-status');if(!navigator.geolocation){status.textContent='Geolocation is not supported by this browser.';return}status.textContent='Getting precise GPS location…';navigator.geolocation.getCurrentPosition(pos=>setLocation(pos.coords.latitude,pos.coords.longitude,pos.coords.accuracy),err=>{status.textContent=err.code===1?'Location permission denied. Please allow location access.':'Unable to get location. Try again.',console.warn(err)},{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
function initPhoto(){document.querySelector('#disaster-photo')?.addEventListener('change',async e=>{const file=e.target.files?.[0];const box=document.querySelector('#photo-preview');if(!file){box.hidden=true;box.innerHTML='';return}if(!file.type.startsWith('image/'))return;box.hidden=false;box.innerHTML='<span>Processing photo…</span>';try{const data=await compressImage(file);box.innerHTML=`<img src="${data}" alt="Selected disaster evidence"><button type="button" class="btn" id="remove-photo">Remove photo</button>`;box.dataset.data=data;document.querySelector('#remove-photo').onclick=()=>{e.target.value='';box.hidden=true;box.innerHTML='';delete box.dataset.data}}catch(err){box.textContent='Could not process this image.'}})}
async function createChallenge(e){e.preventDefault();const f=e.target,d=load();const photo=document.querySelector('#photo-preview')?.dataset.data||'';const c={id:'CH-'+Math.floor(1000+Math.random()*8999),title:f.title.value,category:f.category.value,district:f.district.value,priority:f.priority.value,status:'New',description:f.description.value,created:new Date().toLocaleString(),student:'Unassigned',support:'Open',photo,latitude:f.latitude.value?Number(f.latitude.value):null,longitude:f.longitude.value?Number(f.longitude.value):null,accuracy:f.accuracy.value?Number(f.accuracy.value):null};d.challenges.push(c);save(d);sendN8n(c);f.reset();document.querySelector('#location-status').textContent='Location not added yet.';document.querySelector('#map-preview').hidden=true;document.querySelector('#photo-preview').hidden=true;document.querySelector('#photo-preview').innerHTML='';delete document.querySelector('#photo-preview').dataset.data;toast('Challenge reported with evidence • smart routing triggered');renderCitizen()}
function simulateIoT(){const d=load();const water=Math.floor(45+Math.random()*65),temp=(24+Math.random()*9).toFixed(1),alert=water>=85;const x={device:'ESP32-WATER-01',water,temp,alert,time:new Date().toLocaleTimeString()};d.telemetry.push(x);if(alert)d.challenges.push({id:'IOT-'+Date.now().toString().slice(-5),title:'Automated high water-level alert',category:'Flood',district:'East Singhbhum',priority:'High',status:'Routing',description:`ESP32 water-level sensor crossed threshold at ${water}%. Immediate field verification recommended.`,created:x.time,student:'Unassigned',support:'Auto-created by IoT'});save(d);toast(alert?'⚠ IoT threshold breach created a challenge':'IoT telemetry received');renderGov()}
function initForm(){document.querySelector('#challenge-form')?.addEventListener('submit',createChallenge)}
window.addEventListener('DOMContentLoaded',()=>{initForm();initLocation();initPhoto();renderStudent();renderCitizen();renderIndustry();renderGov();document.querySelector('#save-n8n')?.addEventListener('click',()=>{localStorage.setItem('n8n_webhook',document.querySelector('#n8n-url').value.trim());toast('n8n webhook saved')})});
